// <auto-generated />
using System;
using FenBaoApiTest.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FenBaoApiTest.Migrations
{
    [DbContext(typeof(AppDbcontext))]
    [Migration("20201216093944_f3")]
    partial class f3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FenBaoApiTest.Models.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ActivityEndTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ActivityScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ActivityTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ActivtyAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ActivtyStatus")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("ParticipantsNum")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("activities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e109e697-a99f-40ab-b929-cee7b1338bf2"),
                            ActivityScore = 2.0m,
                            ActivityTime = new DateTime(2020, 12, 16, 17, 39, 43, 603, DateTimeKind.Local).AddTicks(3795),
                            ActivtyAddress = "博文楼",
                            ActivtyStatus = true,
                            Name = "1",
                            ParticipantsNum = 2
                        });
                });

            modelBuilder.Entity("FenBaoApiTest.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CommentText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.ToTable("comments");
                });

            modelBuilder.Entity("FenBaoApiTest.Models.Comment", b =>
                {
                    b.HasOne("FenBaoApiTest.Models.Activity", "activity")
                        .WithMany("Comments")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
